baseURL = "http://jefforshalick.netlify.com"
languageCode = "en-us"
title = "Jeff Orshalick"
theme = "creativePortfolio"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "blue"
  description = "Jeff Orshalick - Designer"
  copyright = "hi@jefforshalick.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Portfolio"
  url = ""

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [params.social]
  linkedin      = "https://www.linkedin.com/in/jefforshalick/"
  dribbble      = "https://dribbble.com/jefforshalick/"
  instagram     = "https://www.instagram.com/jefforshalick/"