---
upload_path: "/static/img/portfolio"
frontmatter_file_url_template: "/static/img/portfolio"
body_file_url_template: "/static/img/portfolio"
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
  portfolio:
    default_front_matter_template: portfolio
version: 0.31.1
